#!/bin/bash

case "$1" in
  start)
    echo "Starting SiLCC"
    su silcc
    cd /home/silcc/SiLCC
    paster serve --daemon prod.ini
    exit
    ;;
  stop)
    echo "Stopping SiLCC"
    su silcc
    cd /home/silcc/SILCC
    paster serve prod.ini stop
    exit
    ;;
  *)
    echo "Usage: /etc/init.d/silcc {start|stop}"
    exit 1
    ;;
esac

exit 0
