#!/bin/bash

case "$1" in
  start)
    echo "Starting SiLCC"
    echo "export HOME=/home/silcc;cd /home/silcc/SiLCC;paster serve --daemon prod.ini" | sudo -u silcc bash
    ;;
  stop)
    echo "Stopping SiLCC"
    echo "export HOME=/home/silcc;cd /home/silcc/SiLCC;paster serve prod.ini stop" | sudo -u silcc bash
    ;;
  *)
    echo "Usage: /etc/init.d/silcc {start|stop}"
    exit 1
    ;;
esac

exit 0
